[providers]
nixpkgs = ['python310', 'python310Packages.pip']

[phases.install]
cmds = [
  'pip install --user -r requirements.txt'
]

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = 'python app.py'
