[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn app_fresh:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PYTHONPATH = "/app"
FLASK_ENV = "production"
